export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_FIRST_STEP = "ADD_FIRST_STEP";
export const ADD_SECOND_STEP = "ADD_SECOND_STEP";
export const ADD_THIRD_STEP = "ADD_THIRD_STEP";
export const ADD_FOUR_STEP = "ADD_FOUR_STEP ";

export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";

//  action commandes
export const ADD_COMMANDE = "ADD_COMMANDE";
export const ADD_COMMANDE_SUCCESS = "ADD_COMMANDE_SUCCESS";
export const GET_COMMANDE_LIST = "GET_COMMANDE_LIST";
export const GET_COMMANDE_LIST_SUCCESS = "GET_COMMANDE_LIST_SUCCESS";
export const UPDATE_COMMANDE = "UPDATE_COMMANDE";
export const DELETE_COMMANDE = "DELETE_COMMANDE";
export const SET_SELECTED_ARTICLE ="SET_SELECTED_ARTICLE";
export const UPDATE_QTE_ARTICLE ="UPDATE_QTE_ARTICLE";
export const DELETE_SELECTED_ARTICLE ="DELETE_SELECTED_ARTICLE";


//action Details commandes
export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";

// action articles 
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

//action suivies
export const ADD_SUIVIE = "ADD_SUIVIE";
export const ADD_SUIVIE_SUCCESS = "ADD_SUIVIE_SUCCESS";
export const GET_SUIVIE_LIST = "GET_SUIVIE_LIST";
export const GET_SUIVIE_LIST_SUCCESS = "GET_SUIVIE_LIST_SUCCESS";
export const UPDATE_SUIVIE = "UPDATE_SUIVIE";
export const DELETE_SUIVIE = "DELETE_SUIVIE";

//action paiements
export const ADD_PAIEMENT = "ADD_PAIEMENT";
export const ADD_PAIEMENT_SUCCESS = "ADD_PAIEMENT_SUCCESS";
export const GET_PAIEMENT_LIST = "GET_PAIEMENT_LIST";
export const GET_PAIEMENT_LIST_SUCCESS = "GET_PAIEMENT_LIST_SUCCESS";
export const UPDATE_PAIEMENT= "UPDATE_PAIEMENT";
export const DELETE_PAIEMENT = "DELETE_PAIEMENT";


//action Produits
export const ADD_PRODUIT = "ADD_PRODUIT";
export const GET_PRODUIT_LIST = "GET_PRODUIT_LIST";
export const GET_PRODUIT_LIST_SUCCESS = "GET_PRODUIT_LIST_SUCCESS";
export const UPDATE_PRODUIT = "UPDATE_PRODUIT";
export const DELETE_PRODUIT = "DELETE_PRODUIT";

//actions Adresses
export const ADD_ADRESSE = "ADD_ADRESSE";
export const GET_ADRESSE_LIST = "GET_ADRESSE_LIST";
export const GET_ADRESSE_LIST_SUCCESS = "GET_ADRESSE_LIST_SUCCESS";
export const UPDATE_ADRESSE = "UPDATE_ADRESSE";
export const DELETE_ADRESSE = "DELETE_ADRESSE";


