export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_FIRST_STEP = "ADD_FIRST_STEP";
export const ADD_SECOND_STEP = "ADD_SECOND_STEP";
export const ADD_THIRD_STEP = "ADD_THIRD_STEP";
export const ADD_FOUR_STEP = "ADD_FOUR_STEP ";

export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";

