export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_FIRST_STEP = "ADD_FIRST_STEP";
export const ADD_SECOND_STEP = "ADD_SECOND_STEP";
export const ADD_THIRD_STEP = "ADD_THIRD_STEP";
export const ADD_FOUR_STEP = "ADD_FOUR_STEP ";

export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";

//  action commandes
export const ADD_COMMANDE = "ADD_COMMANDE";
export const ADD_COMMANDE_SUCCESS = "ADD_COMMANDE_SUCCESS";
export const GET_COMMANDE_LIST = "GET_COMMANDE_LIST";
export const GET_COMMANDE_LIST_SUCCESS = "GET_COMMANDE_LIST_SUCCESS";
export const UPDATE_COMMANDE = "UPDATE_COMMANDE";
export const DELETE_COMMANDE = "DELETE_COMMANDE";

// action articles 
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

